### ISSUE TITLE
i'm getting 412s instead of 304s back for GETs

### ISSUE THREAD

**Issue by michielbdejong** [remotestorage/rs-serve#1]
when i open https://unht-beta.heahdk.net/storage/michiel/public/www/index.html in FF or Chrome and soft-refresh the page several times, i see the contents appear and disappear and appear and disappear.. on the refreshes where it disappears, i see 412s coming back, which i guess should be 304s instead:
"if the request method was GET or HEAD, the server SHOULD respond with a 304 (Not Modified) response, including the cache- related header fields (particularly ETag) of one of the entities that matched. For all other request methods, the server MUST respond with a status of 412 (Precondition Failed). "
http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

**Comment by nilclass** [comment]
Ok. That conflicts with

> GET requests MAY have an 'If-None-Match' header [HTTP], and SHOULD be responded to with a 412 response if that includes the document or folder's current version.

https://github.com/remotestorage/spec/blob/master/draft-dejong-remotestorage-01.txt#L249

**Comment by michielbdejong** [comment]
bummer :(
